#
# JBZoo Toolbox - Composer-Graph
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Composer-Graph
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Composer-Graph
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: 8.0
    - php: nightly

env:
  matrix:
    - JBZOO_COMPOSER_UPDATE_FLAGS="--prefer-lowest --prefer-stable"
    - JBZOO_COMPOSER_UPDATE_FLAGS=""

before_script:
  - composer self-update

script:
  - make build    --no-print-directory
  - make test-all --no-print-directory

after_script:
  - make report-coveralls

deploy:
  provider: releases
  token:
    secure: CQf+RyuuwZEbdgGU6cNsAX07FUIt/2J1OmdI+V71kG2X2LVYjhFB1sjnK3+82n8EKEfzrpCEIKUN7ZiZT5TakZwhn2TQCdKX16JYjEAjhQWY64/+p6IZIClkYDjffH/5LDsvL+ovVmr9u+aEpLFwmLC5Ug+cMO+yAEQf7Re7kwS+H5gZUnbz9sj3ZzkVF08MjLmxmWfEvOAzwzkGjzi5cPhLVeKVwyeat9dn/2na+eFKQ9s9Ym9MdUKZN5Uv9HqypT1BMKYEhzu0OnxHSBI8/e3cdFmEnzIvUSk/c1GXhM+uBJ6KSBSdEmmBBXfhSGh9t9y6caf9Kdg339nTKspk9xJf3HqgcKadpcZzd+ap46qsTENqiqi1cxA7i0oomoxKKkMLCxmhqDOV48ucMbLuOYhQmizW7OV1OwxvdYowgbWEtYqauoSwFD89ueDPk46Ab0sdpiBXn2jV//rJZFNKS7W5ZcOaLYovpR5UnrKQ/IKn5xYoDCMfLDHQ/PMVNb6cIW3ynvCPOMIwBcz079PrbNhkgJKmjgl8/gkPZoNMfoAAbwMJE7MI0Gip0kSCdx9TjhybKVmE3B+egEgEWfgDy4z9LINOjzHfSkJPPgWd37HukTAzrc+sTB2v11vEKvqvPoPeBkCm3Z14u/rjObYPN7LXDmsGk24nXa96ac+SArg=
  file: "./build/composer-graph.phar"
  on:
    tags: true
  overwrite: true
  skip_cleanup: true
