<?php

/**
 * JBZoo Toolbox - Composer-Graph
 *
 * This file is part of the JBZoo Toolbox project.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    Composer-Graph
 * @license    MIT
 * @copyright  Copyright (C) JBZoo.com, All rights reserved.
 * @link       https://github.com/JBZoo/Composer-Graph
 */

namespace JBZoo\PHPUnit;

/**
 * Class GraphBuildTest
 *
 * @package JBZoo\PHPUnit
 */
class GraphBuildTest extends AbstractGraphTest
{
    public function testHelpInReadme()
    {
        $result = $this->task('--help');
        $readme = file_get_contents(PROJECT_ROOT . '/README.md');

        isContain($result, $readme);
    }

    public function testSelfMinimal()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    jbzoo__composer_g_raph ==> jbzoo__data;',
            '    jbzoo__composer_g_raph ==> jbzoo__mermaid_php;',
            '    jbzoo__composer_g_raph ==> jbzoo__utils;',
            '    jbzoo__composer_g_raph ==> symfony__console;',
            '    symfony__console-->symfony__polyfill_mbstring;',
            '    symfony__console-->symfony__polyfill_php73;',
            '    symfony__console-->symfony__polyfill_php80;',
            '    symfony__console-->symfony__service_contracts;',
            '    symfony__service_contracts-->psr__container;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__composer_g_raph("jbzoo/composer-graph");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__data("jbzoo/data");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php");',
            '        jbzoo__utils("jbzoo/utils");',
            '        psr__container("psr/container");',
            '        symfony__console("symfony/console");',
            '        symfony__polyfill_mbstring("symfony/polyfill-mbstring");',
            '        symfony__polyfill_php73("symfony/polyfill-php73");',
            '        symfony__polyfill_php80("symfony/polyfill-php80");',
            '        symfony__service_contracts("symfony/service-contracts");',
            '    end',
        ]), $this->buildGraph([
            'composer-json' => PROJECT_ROOT . "/composer.json",
            'composer-lock' => PROJECT_ROOT . "/composer.lock",
        ], __FUNCTION__));
    }

    public function testEmpty()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    subgraph "Your Package"',
            '    end',
        ]), $this->buildGraph([
            'show-php'           => null,
            'show-ext'           => null,
            'show-dev'           => null,
            'show-suggests'      => null,
            'show-lib-versions'  => null,
            'show-link-versions' => null,
        ], __FUNCTION__));
    }

    public function testSimpleDeps()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    test__main == "4.0.x-dev" ==> jbzoo__assets;',
            '',
            '    subgraph "Your Package"',
            '        test__main("test/main");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__assets("jbzoo/assets@3.0.x-dev");',
            '    end',
        ]), $this->buildGraph([
            'show-php'           => null,
            'show-ext'           => null,
            'show-dev'           => null,
            'show-suggests'      => null,
            'show-lib-versions'  => null,
            'show-link-versions' => null,
        ], __FUNCTION__));
    }

    public function testNestedReq()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    jbzoo__assets-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__assets-->|">=7.2"|PHP;',
            '    jbzoo__data-->ext_json;',
            '    jbzoo__data-->|"^7.2"|PHP;',
            '    test__main == "4.0.x-dev" ==> jbzoo__assets;',
            '',
            '    subgraph "Your Package"',
            '        test__main("test/main");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__assets("jbzoo/assets@3.0.x-dev");',
            '        jbzoo__data("jbzoo/data@4.0.x-dev");',
            '    end',
            '    subgraph "PHP Platform"',
            '        PHP("PHP");',
            '        ext_json("ext-json");',
            '    end',
        ]), $this->buildGraph([
            'show-php'           => null,
            'show-ext'           => null,
            'show-dev'           => null,
            'show-suggests'      => null,
            'show-lib-versions'  => null,
            'show-link-versions' => null,
        ], __FUNCTION__));
    }

    public function testJBZooToolbox()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    2bj__phanybar-->|">=5.3.0"|PHP;',
            '    amphp__amp-->|">=7"|PHP;',
            '    amphp__byte_stream-->|"^2"|amphp__amp;',
            '    codedungeon__phpunit_result_printer-->|"^0.11.2"|hassankhan__config;',
            '    codedungeon__phpunit_result_printer-->|"^1.0"|2bj__phanybar;',
            '    codedungeon__phpunit_result_printer-->|"^1.10.2"|codedungeon__php_cli_colors;',
            '    codedungeon__phpunit_result_printer-->|"^2.7|^3.0|^4.0|^5.0"|symfony__yaml;',
            '    codedungeon__phpunit_result_printer-->|"^7.1"|PHP;',
            '    composer__semver-->|"^5.3.2 || ^7.0"|PHP;',
            '    composer__xdebug_handler-->|"^1.0"|psr__log;',
            '    composer__xdebug_handler-->|"^5.3.2 || ^7.0 || ^8.0"|PHP;',
            '    doctrine__annotations-->ext_tokenizer;',
            '    doctrine__annotations-->|"1.*"|doctrine__lexer;',
            '    doctrine__annotations-->|"^7.1 || ^8.0"|PHP;',
            '    doctrine__instantiator-->|"^7.1 || ^8.0"|PHP;',
            '    doctrine__lexer-->|"^7.2 || ^8.0"|PHP;',
            '    felixfbecker__advanced_json_rpc-->|">=7.0"|PHP;',
            '    felixfbecker__advanced_json_rpc-->|"^1.0 || ^2.0"|netresearch__jsonmapper;',
            '    felixfbecker__advanced_json_rpc-->|"^4.0.0 || ^5.0.0"|phpdocumentor__reflection_docblock;',
            '    felixfbecker__language_server_protocol-->|"^7.0"|PHP;',
            '    friendsofphp__php_cs_fixer-->ext_json;',
            '    friendsofphp__php_cs_fixer-->ext_tokenizer;',
            '    friendsofphp__php_cs_fixer-->|"^1.0"|symfony__polyfill_php70;',
            '    friendsofphp__php_cs_fixer-->|"^1.2"|composer__xdebug_handler;',
            '    friendsofphp__php_cs_fixer-->|"^1.2"|doctrine__annotations;',
            '    friendsofphp__php_cs_fixer-->|"^1.3"|php_cs_fixer__diff;',
            '    friendsofphp__php_cs_fixer-->|"^1.4"|composer__semver;',
            '    friendsofphp__php_cs_fixer-->|"^1.4"|symfony__polyfill_php72;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__event_dispatcher;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__filesystem;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__finder;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__options_resolver;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__process;',
            '    friendsofphp__php_cs_fixer-->|"^3.0 || ^4.0 || ^5.0"|symfony__stopwatch;',
            '    friendsofphp__php_cs_fixer-->|"^3.4.17 || ^4.1.6 || ^5.0"|symfony__console;',
            '    friendsofphp__php_cs_fixer-->|"^5.6 || ^7.0"|PHP;',
            '    friendsofphp__php_cs_fixer-. "suggest" .-> ext_dom;',
            '    friendsofphp__php_cs_fixer-. "suggest" .-> ext_mbstring;',
            '    friendsofphp__php_cs_fixer-. "suggest" .-> php_cs_fixer__phpunit_constraint_isidenticalstring;',
            '    friendsofphp__php_cs_fixer-. "suggest" .-> php_cs_fixer__phpunit_constraint_xmlmatchesxsd;',
            '    friendsofphp__php_cs_fixer-. "suggest" .-> symfony__polyfill_mbstring;',
            '    guzzlehttp__guzzle-->ext_json;',
            '    guzzlehttp__guzzle-->|">=5.5"|PHP;',
            '    guzzlehttp__guzzle-->|"^1.0"|guzzlehttp__promises;',
            '    guzzlehttp__guzzle-->|"^1.17.0"|symfony__polyfill_intl_idn;',
            '    guzzlehttp__guzzle-->|"^1.6.1"|guzzlehttp__psr7;',
            '    guzzlehttp__guzzle-. "suggest" .-> psr__log;',
            '    guzzlehttp__promises-->|">=5.5.0"|PHP;',
            '    guzzlehttp__psr7-->|">=5.4.0"|PHP;',
            '    guzzlehttp__psr7-->|"^2.0.5 || ^3.0.0"|ralouphie__getallheaders;',
            '    guzzlehttp__psr7-->|"~1.0"|psr__http_message;',
            '    guzzlehttp__psr7-. "suggest" .-> zendframework__zend_httphandlerrunner;',
            '    hassankhan__config-->|">=5.3.0"|PHP;',
            '    hassankhan__config-. "suggest" .-> symfony__yaml;',
            '    jakub_onderka__php_console_color-->|">=5.4.0"|PHP;',
            '    jakub_onderka__php_console_highlighter-->ext_tokenizer;',
            '    jakub_onderka__php_console_highlighter-->|">=5.4.0"|PHP;',
            '    jakub_onderka__php_console_highlighter-->|"~0.2"|jakub_onderka__php_console_color;',
            '    jbzoo__assets-->|"3.0.x-dev"|jbzoo__less;',
            '    jbzoo__assets-->|"3.0.x-dev"|jbzoo__path;',
            '    jbzoo__assets-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__assets-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__assets-->|">=7.2"|PHP;',
            '    jbzoo__codestyle-->|">=7.2"|PHP;',
            '    jbzoo__codestyle-->|"^0.12.32"|phpstan__phpstan;',
            '    jbzoo__codestyle-->|"^1.5.1"|davidrjonas__composer_lock_diff;',
            '    jbzoo__codestyle-->|"^2.0.0"|maglnet__composer_require_checker;',
            '    jbzoo__codestyle-->|"^2.16.3"|friendsofphp__php_cs_fixer;',
            '    jbzoo__codestyle-->|"^2.2.0"|php_coveralls__php_coveralls;',
            '    jbzoo__codestyle-->|"^2.2.0"|povils__phpmnd;',
            '    jbzoo__codestyle-->|"^2.8.2"|phpmd__phpmd;',
            '    jbzoo__codestyle-->|"^3.0.4"|phan__phan;',
            '    jbzoo__codestyle-->|"^3.1.2"|nette__neon;',
            '    jbzoo__codestyle-->|"^3.12.1"|vimeo__psalm;',
            '    jbzoo__codestyle-->|"^3.5.5"|squizlabs__php_codesniffer;',
            '    jbzoo__codestyle-->|"^4.1||^5.0"|sebastian__phpcpd;',
            '    jbzoo__codestyle-->|"^5.0||^6.0"|phploc__phploc;',
            '    jbzoo__codestyle-->|"^6.0.3"|sensiolabs__security_checker;',
            '    jbzoo__codestyle-->|"^9.3.5"|phpcompatibility__php_compatibility;',
            '    jbzoo__composer_g_raph-->|"2.0.x-dev"|jbzoo__mermaid_php;',
            '    jbzoo__composer_g_raph-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__composer_g_raph-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__composer_g_raph-->|">=7.2"|PHP;',
            '    jbzoo__composer_g_raph-->|"^4.4||^5.0"|symfony__console;',
            '    jbzoo__composer_g_raph-->|"^4.4||^5.0"|symfony__process;',
            '    jbzoo__data-->ext_json;',
            '    jbzoo__data-->|"^7.2"|PHP;',
            '    jbzoo__data-. "suggest" .-> jbzoo__utils;',
            '    jbzoo__data-. "suggest" .-> symfony__yaml;',
            '    jbzoo__event-->|">=7.2"|PHP;',
            '    jbzoo__http_client-->ext_json;',
            '    jbzoo__http_client-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__http_client-->|">=7.2"|PHP;',
            '    jbzoo__http_client-. "suggest" .-> guzzlehttp__guzzle;',
            '    jbzoo__http_client-. "suggest" .-> jbzoo__event;',
            '    jbzoo__http_client-. "suggest" .-> rmccue__requests;',
            '    jbzoo__image-->ext_ctype;',
            '    jbzoo__image-->ext_exif;',
            '    jbzoo__image-->ext_gd;',
            '    jbzoo__image-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__image-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__image-->|">=7.2"|PHP;',
            '    jbzoo__less-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__less-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__less-->|">=7.2"|PHP;',
            '    jbzoo__less-->|"^3.0.0"|wikimedia__less.php;',
            '    jbzoo__mermaid_php-->ext_json;',
            '    jbzoo__mermaid_php-->|">=7.2"|PHP;',
            '    jbzoo__path-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__path-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__path-->|">=7.2"|PHP;',
            '    jbzoo__phpunit-->ext_filter;',
            '    jbzoo__phpunit-->|"^0.28.0"|codedungeon__phpunit_result_printer;',
            '    jbzoo__phpunit-->|"^3.3.0"|ulrichsg__getopt_php;',
            '    jbzoo__phpunit-->|"^6.0.1||^7.0"|phpunit__phpcov;',
            '    jbzoo__phpunit-->|"^7.2"|PHP;',
            '    jbzoo__phpunit-->|"^8.5||^9.1"|phpunit__phpunit;',
            '    jbzoo__toolbox == "1.0.x-dev" ==> jbzoo__composer_g_raph;',
            '    jbzoo__toolbox == "2.0.x-dev" ==> jbzoo__codestyle;',
            '    jbzoo__toolbox == "2.0.x-dev" ==> jbzoo__mermaid_php;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__assets;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__event;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__http_client;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__less;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__path;',
            '    jbzoo__toolbox == "4.0.x-dev" ==> jbzoo__data;',
            '    jbzoo__toolbox == "4.0.x-dev" ==> jbzoo__phpunit;',
            '    jbzoo__toolbox == "4.0.x-dev" ==> jbzoo__utils;',
            '    jbzoo__toolbox == "5.0.x-dev" ==> jbzoo__image;',
            '    jbzoo__toolbox == ">=7.2" ==> PHP;',
            '    jbzoo__toolbox == "^1.7.0" ==> rmccue__requests;',
            '    jbzoo__toolbox == "^6.4.1" ==> guzzlehttp__guzzle;',
            '    jbzoo__toolbox == "dev-master" ==> roave__security_advisories;',
            '    jbzoo__utils-->ext_filter;',
            '    jbzoo__utils-->ext_gd;',
            '    jbzoo__utils-->ext_intl;',
            '    jbzoo__utils-->ext_mbstring;',
            '    jbzoo__utils-->ext_posix;',
            '    jbzoo__utils-->|">=7.2"|PHP;',
            '    jbzoo__utils-. "suggest" .-> jbzoo__data;',
            '    jbzoo__utils-. "suggest" .-> symfony__polyfill_mbstring;',
            '    jbzoo__utils-. "suggest" .-> symfony__process;',
            '    maglnet__composer_require_checker-->ext_json;',
            '    maglnet__composer_require_checker-->ext_phar;',
            '    maglnet__composer_require_checker-->|"^3.4.17 | ^4.1.6"|symfony__console;',
            '    maglnet__composer_require_checker-->|"^4.0"|nikic__php_parser;',
            '    maglnet__composer_require_checker-->|"^4.1"|webmozart__glob;',
            '    maglnet__composer_require_checker-->|"^7.1"|PHP;',
            '    microsoft__tolerant_php_parser-->|">=7.0"|PHP;',
            '    myclabs__deep_copy-->|"^7.1 || ^8.0"|PHP;',
            '    netresearch__jsonmapper-->ext_json;',
            '    netresearch__jsonmapper-->ext_pcre;',
            '    netresearch__jsonmapper-->ext_reflection;',
            '    netresearch__jsonmapper-->ext_spl;',
            '    netresearch__jsonmapper-->|">=5.6"|PHP;',
            '    nette__neon-->ext_iconv;',
            '    nette__neon-->ext_json;',
            '    nette__neon-->|">=7.1"|PHP;',
            '    nikic__php_parser-->ext_tokenizer;',
            '    nikic__php_parser-->|">=7.0"|PHP;',
            '    ocramius__package_versions-->|"^1.0.0"|composer_plugin_api;',
            '    ocramius__package_versions-->|"^7.1.0"|PHP;',
            '    openlss__lib_array2xml-->|">=5.3.2"|PHP;',
            '    paragonie__random_compat-->|"^7"|PHP;',
            '    paragonie__random_compat-. "suggest" .-> ext_libsodium;',
            '    pdepend__pdepend-->|">=5.3.7"|PHP;',
            '    pdepend__pdepend-->|"^2.3.0|^3|^4|^5"|symfony__config;',
            '    pdepend__pdepend-->|"^2.3.0|^3|^4|^5"|symfony__dependency_injection;',
            '    pdepend__pdepend-->|"^2.3.0|^3|^4|^5"|symfony__filesystem;',
            '    phan__phan-->ext_filter;',
            '    phan__phan-->ext_json;',
            '    phan__phan-->ext_tokenizer;',
            '    phan__phan-->|"0.0.20"|microsoft__tolerant_php_parser;',
            '    phan__phan-->|"^1.11.0"|symfony__polyfill_mbstring;',
            '    phan__phan-->|"^1.3.2"|composer__xdebug_handler;',
            '    phan__phan-->|"^1.4|^2.0|^3.0"|composer__semver;',
            '    phan__phan-->|"^1.6.0|^2.0"|netresearch__jsonmapper;',
            '    phan__phan-->|"^2.3|^3.0|^4.0|^5.0"|symfony__console;',
            '    phan__phan-->|"^3.0.4"|felixfbecker__advanced_json_rpc;',
            '    phan__phan-->|"^5.0"|sabre__event;',
            '    phan__phan-->|"^7.2.0"|PHP;',
            '    phan__phan-. "suggest" .-> ext_ast;',
            '    phan__phan-. "suggest" .-> ext_iconv;',
            '    phan__phan-. "suggest" .-> ext_igbinary;',
            '    phan__phan-. "suggest" .-> ext_mbstring;',
            '    phar_io__manifest-->ext_dom;',
            '    phar_io__manifest-->ext_phar;',
            '    phar_io__manifest-->|"^2.0"|phar_io__version;',
            '    phar_io__manifest-->|"^5.6 || ^7.0"|PHP;',
            '    phar_io__version-->|"^5.6 || ^7.0"|PHP;',
            '    php_coveralls__php_coveralls-->ext_json;',
            '    php_coveralls__php_coveralls-->ext_simplexml;',
            '    php_coveralls__php_coveralls-->|"^1.0"|psr__log;',
            '    php_coveralls__php_coveralls-->|"^2.0 || ^3.0 || ^4.0 || ^5.0"|symfony__stopwatch;',
            '    php_coveralls__php_coveralls-->|"^2.0.5 || ^3.0 || ^4.0 || ^5.0"|symfony__yaml;',
            '    php_coveralls__php_coveralls-->|"^2.1 || ^3.0 || ^4.0 || ^5.0"|symfony__config;',
            '    php_coveralls__php_coveralls-->|"^2.1 || ^3.0 || ^4.0 || ^5.0"|symfony__console;',
            '    php_coveralls__php_coveralls-->|"^5.5 || ^7.0"|PHP;',
            '    php_coveralls__php_coveralls-->|"^6.0"|guzzlehttp__guzzle;',
            '    php_coveralls__php_coveralls-. "suggest" .-> symfony__http_kernel;',
            '    php_cs_fixer__diff-->|"^5.6 || ^7.0"|PHP;',
            '    phpcompatibility__php_compatibility-->|">=5.3"|PHP;',
            '    phpcompatibility__php_compatibility-->|"^2.3 || ^3.0.2"|squizlabs__php_codesniffer;',
            '    phpcompatibility__php_compatibility-. "suggest" .-> dealerdirect__phpcodesniffer_composer_installer;',
            '    phpcompatibility__php_compatibility-. "suggest" .-> roave__security_advisories;',
            '    phpdocumentor__reflection_common-->|"^7.2 || ^8.0"|PHP;',
            '    phpdocumentor__reflection_docblock-->|"^1"|webmozart__assert;',
            '    phpdocumentor__reflection_docblock-->|"^1.0"|phpdocumentor__type_resolver;',
            '    phpdocumentor__reflection_docblock-->|"^2.0"|phpdocumentor__reflection_common;',
            '    phpdocumentor__reflection_docblock-->|"^7.1"|ext_filter;',
            '    phpdocumentor__reflection_docblock-->|"^7.2"|PHP;',
            '    phpdocumentor__type_resolver-->|"^2.0"|phpdocumentor__reflection_common;',
            '    phpdocumentor__type_resolver-->|"^7.2 || ^8.0"|PHP;',
            '    phploc__phploc-->|"^1.1"|sebastian__finder_facade;',
            '    phploc__phploc-->|"^2.0"|sebastian__version;',
            '    phploc__phploc-->|"^4.0"|symfony__console;',
            '    phploc__phploc-->|"^7.2"|PHP;',
            '    phpmd__phpmd-->ext_xml;',
            '    phpmd__phpmd-->|">=5.3.9"|PHP;',
            '    phpmd__phpmd-->|"^1.0"|composer__xdebug_handler;',
            '    phpmd__phpmd-->|"^2.7.1"|pdepend__pdepend;',
            '    phpspec__prophecy-->|"^1.0.2"|doctrine__instantiator;',
            '    phpspec__prophecy-->|"^1.0|^2.0|^3.0|^4.0"|sebastian__recursion_context;',
            '    phpspec__prophecy-->|"^1.2.3|^2.0|^3.0|^4.0"|sebastian__comparator;',
            '    phpspec__prophecy-->|"^2.0|^3.0.2|^4.0|^5.0"|phpdocumentor__reflection_docblock;',
            '    phpspec__prophecy-->|"^5.3|^7.0"|PHP;',
            '    phpstan__phpstan-->|"^7.1"|PHP;',
            '    phpunit__php_code_coverage-->ext_dom;',
            '    phpunit__php_code_coverage-->ext_xmlwriter;',
            '    phpunit__php_code_coverage-->|"^1.0.1"|sebastian__code_unit_reverse_lookup;',
            '    phpunit__php_code_coverage-->|"^1.1.3"|theseer__tokenizer;',
            '    phpunit__php_code_coverage-->|"^1.2.1"|phpunit__php_text_template;',
            '    phpunit__php_code_coverage-->|"^2.0.1"|sebastian__version;',
            '    phpunit__php_code_coverage-->|"^2.0.2"|phpunit__php_file_iterator;',
            '    phpunit__php_code_coverage-->|"^3.1.1"|phpunit__php_token_stream;',
            '    phpunit__php_code_coverage-->|"^4.2.2"|sebastian__environment;',
            '    phpunit__php_code_coverage-->|"^7.2"|PHP;',
            '    phpunit__php_code_coverage-. "suggest" .-> ext_xdebug;',
            '    phpunit__php_file_iterator-->|"^7.1"|PHP;',
            '    phpunit__php_text_template-->|">=5.3.3"|PHP;',
            '    phpunit__php_timer-->|"^7.1"|PHP;',
            '    phpunit__php_token_stream-->ext_tokenizer;',
            '    phpunit__php_token_stream-->|"^7.1"|PHP;',
            '    phpunit__phpcov-->|"^1.1"|sebastian__finder_facade;',
            '    phpunit__phpcov-->|"^2.0"|sebastian__version;',
            '    phpunit__phpcov-->|"^3.0 || ^4.0"|symfony__console;',
            '    phpunit__phpcov-->|"^3.0"|sebastian__diff;',
            '    phpunit__phpcov-->|"^7.0"|phpunit__php_code_coverage;',
            '    phpunit__phpcov-->|"^7.2"|PHP;',
            '    phpunit__phpcov-->|"^8.0"|phpunit__phpunit;',
            '    phpunit__phpunit-->ext_dom;',
            '    phpunit__phpunit-->ext_json;',
            '    phpunit__phpunit-->ext_libxml;',
            '    phpunit__phpunit-->ext_mbstring;',
            '    phpunit__phpunit-->ext_xml;',
            '    phpunit__phpunit-->ext_xmlwriter;',
            '    phpunit__phpunit-->|"^1.0.3"|phar_io__manifest;',
            '    phpunit__phpunit-->|"^1.1.3"|sebastian__type;',
            '    phpunit__phpunit-->|"^1.2.0"|doctrine__instantiator;',
            '    phpunit__phpunit-->|"^1.2.1"|phpunit__php_text_template;',
            '    phpunit__phpunit-->|"^1.8.1"|phpspec__prophecy;',
            '    phpunit__phpunit-->|"^1.9.1"|myclabs__deep_copy;',
            '    phpunit__phpunit-->|"^2.0.1"|phar_io__version;',
            '    phpunit__phpunit-->|"^2.0.1"|sebastian__resource_operations;',
            '    phpunit__phpunit-->|"^2.0.1"|sebastian__version;',
            '    phpunit__phpunit-->|"^2.0.2"|phpunit__php_file_iterator;',
            '    phpunit__phpunit-->|"^2.1.2"|phpunit__php_timer;',
            '    phpunit__phpunit-->|"^3.0.0"|sebastian__global_state;',
            '    phpunit__phpunit-->|"^3.0.2"|sebastian__comparator;',
            '    phpunit__phpunit-->|"^3.0.2"|sebastian__diff;',
            '    phpunit__phpunit-->|"^3.0.3"|sebastian__object_enumerator;',
            '    phpunit__phpunit-->|"^3.1.1"|sebastian__exporter;',
            '    phpunit__phpunit-->|"^4.2.2"|sebastian__environment;',
            '    phpunit__phpunit-->|"^7.0.7"|phpunit__php_code_coverage;',
            '    phpunit__phpunit-->|"^7.2"|PHP;',
            '    phpunit__phpunit-. "suggest" .-> ext_soap;',
            '    phpunit__phpunit-. "suggest" .-> ext_xdebug;',
            '    phpunit__phpunit-. "suggest" .-> phpunit__php_invoker;',
            '    povils__phpmnd-->|"^0.4"|jakub_onderka__php_console_highlighter;',
            '    povils__phpmnd-->|"^2.0"|phpunit__php_timer;',
            '    povils__phpmnd-->|"^4.0"|nikic__php_parser;',
            '    povils__phpmnd-->|"^4.0"|symfony__console;',
            '    povils__phpmnd-->|"^4.0"|symfony__finder;',
            '    povils__phpmnd-->|"^7.1"|PHP;',
            '    psr__container-->|">=5.3.0"|PHP;',
            '    psr__http_message-->|">=5.3.0"|PHP;',
            '    psr__log-->|">=5.3.0"|PHP;',
            '    ralouphie__getallheaders-->|">=5.6"|PHP;',
            '    rmccue__requests-->|">=5.2"|PHP;',
            '    sabre__event-->|"^7.1"|PHP;',
            '    sebastian__code_unit_reverse_lookup-->|"^5.6 || ^7.0"|PHP;',
            '    sebastian__comparator-->|"^3.0"|sebastian__diff;',
            '    sebastian__comparator-->|"^3.1"|sebastian__exporter;',
            '    sebastian__comparator-->|"^7.1"|PHP;',
            '    sebastian__diff-->|"^7.1"|PHP;',
            '    sebastian__environment-->|"^7.1"|PHP;',
            '    sebastian__environment-. "suggest" .-> ext_posix;',
            '    sebastian__exporter-->|"^3.0"|sebastian__recursion_context;',
            '    sebastian__exporter-->|"^7.0"|PHP;',
            '    sebastian__finder_facade-->|"^1.6"|theseer__fdomdocument;',
            '    sebastian__finder_facade-->|"^2.3|^3.0|^4.0|^5.0"|symfony__finder;',
            '    sebastian__finder_facade-->|"^7.1"|PHP;',
            '    sebastian__global_state-->|"^1.1.1"|sebastian__object_reflector;',
            '    sebastian__global_state-->|"^3.0"|sebastian__recursion_context;',
            '    sebastian__global_state-->|"^7.2"|PHP;',
            '    sebastian__global_state-. "suggest" .-> ext_uopz;',
            '    sebastian__object_enumerator-->|"^1.1.1"|sebastian__object_reflector;',
            '    sebastian__object_enumerator-->|"^3.0"|sebastian__recursion_context;',
            '    sebastian__object_enumerator-->|"^7.0"|PHP;',
            '    sebastian__object_reflector-->|"^7.0"|PHP;',
            '    sebastian__phpcpd-->ext_dom;',
            '    sebastian__phpcpd-->|"^1.0|^2.0"|sebastian__version;',
            '    sebastian__phpcpd-->|"^1.1"|sebastian__finder_facade;',
            '    sebastian__phpcpd-->|"^2.0"|phpunit__php_timer;',
            '    sebastian__phpcpd-->|"^2.7|^3.0|^4.0"|symfony__console;',
            '    sebastian__phpcpd-->|"^7.1"|PHP;',
            '    sebastian__recursion_context-->|"^7.0"|PHP;',
            '    sebastian__resource_operations-->|"^7.1"|PHP;',
            '    sebastian__type-->|"^7.2"|PHP;',
            '    sebastian__version-->|">=5.6"|PHP;',
            '    sensiolabs__security_checker-->|">=7.1.3"|PHP;',
            '    sensiolabs__security_checker-->|"^1.11"|symfony__polyfill_ctype;',
            '    sensiolabs__security_checker-->|"^2.8|^3.4|^4.2|^5.0"|symfony__console;',
            '    sensiolabs__security_checker-->|"^4.3|^5.0"|symfony__http_client;',
            '    sensiolabs__security_checker-->|"^4.3|^5.0"|symfony__mime;',
            '    squizlabs__php_codesniffer-->ext_simplexml;',
            '    squizlabs__php_codesniffer-->ext_tokenizer;',
            '    squizlabs__php_codesniffer-->ext_xmlwriter;',
            '    squizlabs__php_codesniffer-->|">=5.4.0"|PHP;',
            '    symfony__config-->|">=7.2.5"|PHP;',
            '    symfony__config-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__config-->|"^2.1"|symfony__deprecation_contracts;',
            '    symfony__config-->|"^4.4|^5.0"|symfony__filesystem;',
            '    symfony__config-->|"~1.8"|symfony__polyfill_ctype;',
            '    symfony__config-. "suggest" .-> symfony__yaml;',
            '    symfony__console-->|">=7.1.3"|PHP;',
            '    symfony__console-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__console-->|"^1.1|^2"|symfony__service_contracts;',
            '    symfony__console-->|"^1.8"|symfony__polyfill_php73;',
            '    symfony__console-->|"~1.0"|symfony__polyfill_mbstring;',
            '    symfony__console-. "suggest" .-> psr__log;',
            '    symfony__console-. "suggest" .-> symfony__event_dispatcher;',
            '    symfony__console-. "suggest" .-> symfony__lock;',
            '    symfony__console-. "suggest" .-> symfony__process;',
            '    symfony__dependency_injection-->|">=7.2.5"|PHP;',
            '    symfony__dependency_injection-->|"^1.0"|psr__container;',
            '    symfony__dependency_injection-->|"^1.1.6|^2"|symfony__service_contracts;',
            '    symfony__dependency_injection-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__dependency_injection-->|"^2.1"|symfony__deprecation_contracts;',
            '    symfony__dependency_injection-. "suggest" .-> symfony__config;',
            '    symfony__dependency_injection-. "suggest" .-> symfony__expression_language;',
            '    symfony__dependency_injection-. "suggest" .-> symfony__finder;',
            '    symfony__dependency_injection-. "suggest" .-> symfony__proxy_manager_bridge;',
            '    symfony__dependency_injection-. "suggest" .-> symfony__yaml;',
            '    symfony__deprecation_contracts-->|">=7.1"|PHP;',
            '    symfony__event_dispatcher-->|">=7.1.3"|PHP;',
            '    symfony__event_dispatcher-->|"^1.1"|symfony__event_dispatcher_contracts;',
            '    symfony__event_dispatcher-. "suggest" .-> symfony__dependency_injection;',
            '    symfony__event_dispatcher-. "suggest" .-> symfony__http_kernel;',
            '    symfony__event_dispatcher_contracts-->|"^7.1.3"|PHP;',
            '    symfony__event_dispatcher_contracts-. "suggest" .-> psr__event_dispatcher;',
            '    symfony__event_dispatcher_contracts-. "suggest" .-> symfony__event_dispatcher_implementation;',
            '    symfony__filesystem-->|">=7.2.5"|PHP;',
            '    symfony__filesystem-->|"~1.8"|symfony__polyfill_ctype;',
            '    symfony__finder-->|"^7.1.3"|PHP;',
            '    symfony__http_client-->|">=7.2.5"|PHP;',
            '    symfony__http_client-->|"^1.0"|psr__log;',
            '    symfony__http_client-->|"^1.0|^2"|symfony__service_contracts;',
            '    symfony__http_client-->|"^1.11"|symfony__polyfill_php73;',
            '    symfony__http_client-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__http_client-->|"^2.1.1"|symfony__http_client_contracts;',
            '    symfony__http_client_contracts-->|">=7.2.5"|PHP;',
            '    symfony__http_client_contracts-. "suggest" .-> symfony__http_client_implementation;',
            '    symfony__mime-->|">=7.2.5"|PHP;',
            '    symfony__mime-->|"^1.0"|symfony__polyfill_mbstring;',
            '    symfony__mime-->|"^1.10"|symfony__polyfill_intl_idn;',
            '    symfony__mime-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__options_resolver-->|">=7.2.5"|PHP;',
            '    symfony__options_resolver-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__options_resolver-->|"^2.1"|symfony__deprecation_contracts;',
            '    symfony__polyfill_ctype-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_ctype-. "suggest" .-> ext_ctype;',
            '    symfony__polyfill_intl_idn-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_intl_idn-->|"^1.10"|symfony__polyfill_php72;',
            '    symfony__polyfill_intl_idn-->|"^1.3"|symfony__polyfill_mbstring;',
            '    symfony__polyfill_intl_idn-. "suggest" .-> ext_intl;',
            '    symfony__polyfill_mbstring-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_mbstring-. "suggest" .-> ext_mbstring;',
            '    symfony__polyfill_php70-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_php70-->|"~1.0|~2.0|~9.99"|paragonie__random_compat;',
            '    symfony__polyfill_php72-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_php73-->|">=5.3.3"|PHP;',
            '    symfony__polyfill_php80-->|">=7.0.8"|PHP;',
            '    symfony__process-->|">=7.2.5"|PHP;',
            '    symfony__process-->|"^1.15"|symfony__polyfill_php80;',
            '    symfony__service_contracts-->|">=7.2.5"|PHP;',
            '    symfony__service_contracts-->|"^1.0"|psr__container;',
            '    symfony__service_contracts-. "suggest" .-> symfony__service_implementation;',
            '    symfony__stopwatch-->|">=7.2.5"|PHP;',
            '    symfony__stopwatch-->|"^1.0|^2"|symfony__service_contracts;',
            '    symfony__yaml-->|">=7.2.5"|PHP;',
            '    symfony__yaml-->|"^2.1"|symfony__deprecation_contracts;',
            '    symfony__yaml-->|"~1.8"|symfony__polyfill_ctype;',
            '    symfony__yaml-. "suggest" .-> symfony__console;',
            '    theseer__fdomdocument-->ext_dom;',
            '    theseer__fdomdocument-->lib_libxml;',
            '    theseer__fdomdocument-->|">=5.3.3"|PHP;',
            '    theseer__tokenizer-->ext_dom;',
            '    theseer__tokenizer-->ext_tokenizer;',
            '    theseer__tokenizer-->ext_xmlwriter;',
            '    theseer__tokenizer-->|"^7.0"|PHP;',
            '    ulrichsg__getopt_php-->ext_mbstring;',
            '    ulrichsg__getopt_php-->|">=5.4.0"|PHP;',
            '    vimeo__psalm-->ext_dom;',
            '    vimeo__psalm-->ext_json;',
            '    vimeo__psalm-->ext_libxml;',
            '    vimeo__psalm-->ext_simplexml;',
            '    vimeo__psalm-->ext_tokenizer;',
            '    vimeo__psalm-->|"^1.0 || ^2.0"|netresearch__jsonmapper;',
            '    vimeo__psalm-->|"^1.0"|openlss__lib_array2xml;',
            '    vimeo__psalm-->|"^1.1"|composer__xdebug_handler;',
            '    vimeo__psalm-->|"^1.2"|ocramius__package_versions;',
            '    vimeo__psalm-->|"^1.4 || ^2.0 || ^3.0"|composer__semver;',
            '    vimeo__psalm-->|"^1.4"|felixfbecker__language_server_protocol;',
            '    vimeo__psalm-->|"^1.5"|amphp__byte_stream;',
            '    vimeo__psalm-->|"^2.1"|amphp__amp;',
            '    vimeo__psalm-->|"^2.3"|webmozart__path_util;',
            '    vimeo__psalm-->|"^3.0 || ^4.0"|sebastian__diff;',
            '    vimeo__psalm-->|"^3.0.3"|felixfbecker__advanced_json_rpc;',
            '    vimeo__psalm-->|"^3.4.17 || ^4.1.6 || ^5.0"|symfony__console;',
            '    vimeo__psalm-->|"^4.1"|webmozart__glob;',
            '    vimeo__psalm-->|"^4.3"|nikic__php_parser;',
            '    vimeo__psalm-->|"^7.1.3|^8"|PHP;',
            '    vimeo__psalm-. "suggest" .-> ext_igbinary;',
            '    webmozart__assert-->|"^1.8"|symfony__polyfill_ctype;',
            '    webmozart__assert-->|"^5.3.3 || ^7.0"|PHP;',
            '    webmozart__glob-->|"^2.2"|webmozart__path_util;',
            '    webmozart__glob-->|"^5.3.3|^7.0"|PHP;',
            '    webmozart__path_util-->|">=5.3.3"|PHP;',
            '    webmozart__path_util-->|"~1.0"|webmozart__assert;',
            '    wikimedia__less.php-->|">=7.2.9"|PHP;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__toolbox("jbzoo/toolbox");',
            '    end',
            '    subgraph "Required"',
            '        guzzlehttp__guzzle("guzzlehttp/guzzle@6.5.5");',
            '        jbzoo__assets("jbzoo/assets@3.0.x-dev");',
            '        jbzoo__data("jbzoo/data@4.0.x-dev");',
            '        jbzoo__event("jbzoo/event@3.0.x-dev");',
            '        jbzoo__http_client("jbzoo/http-client@3.0.x-dev");',
            '        jbzoo__image("jbzoo/image@5.0.x-dev");',
            '        jbzoo__less("jbzoo/less@3.0.x-dev");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php@2.0.x-dev");',
            '        jbzoo__path("jbzoo/path@3.0.x-dev");',
            '        jbzoo__utils("jbzoo/utils@4.0.x-dev");',
            '        rmccue__requests("rmccue/requests@v1.7.0");',
            '        roave__security_advisories("roave/security-advisories@dev-master");',
            '        symfony__polyfill_mbstring("symfony/polyfill-mbstring@v1.17.1");',
            '        symfony__process("symfony/process@v5.1.2");',
            '        symfony__yaml("symfony/yaml@v5.1.2");',
            '        wikimedia__less.php("wikimedia/less.php@v3.0.0");',
            '    end',
            '    subgraph "Required Dev"',
            '        2bj__phanybar("2bj/phanybar@v1.0.0");',
            '        amphp__amp("amphp/amp@v2.4.4");',
            '        amphp__byte_stream("amphp/byte-stream@v1.7.3");',
            '        codedungeon__php_cli_colors("codedungeon/php-cli-colors@1.11.0");',
            '        codedungeon__phpunit_result_printer("codedungeon/phpunit-result-printer@0.28.0");',
            '        composer__semver("composer/semver@1.5.1");',
            '        composer__xdebug_handler("composer/xdebug-handler@1.4.2");',
            '        composer_plugin_api(["composer-plugin-api"]);',
            '        davidrjonas__composer_lock_diff("davidrjonas/composer-lock-diff@1.5.1");',
            '        dealerdirect__phpcodesniffer_composer_installer(["dealerdirect/phpcodesniffer-composer-installer"]);',
            '        doctrine__annotations("doctrine/annotations@1.10.3");',
            '        doctrine__instantiator("doctrine/instantiator@1.3.1");',
            '        doctrine__lexer("doctrine/lexer@1.2.1");',
            '        felixfbecker__advanced_json_rpc("felixfbecker/advanced-json-rpc@v3.1.1");',
            '        felixfbecker__language_server_protocol("felixfbecker/language-server-protocol@v1.4.0");',
            '        friendsofphp__php_cs_fixer("friendsofphp/php-cs-fixer@v2.16.4");',
            '        guzzlehttp__promises("guzzlehttp/promises@v1.3.1");',
            '        guzzlehttp__psr7("guzzlehttp/psr7@1.6.1");',
            '        hassankhan__config("hassankhan/config@0.11.2");',
            '        jakub_onderka__php_console_color("jakub-onderka/php-console-color@v0.2");',
            '        jakub_onderka__php_console_highlighter("jakub-onderka/php-console-highlighter@v0.4");',
            '        jbzoo__codestyle("jbzoo/codestyle@2.0.x-dev");',
            '        jbzoo__composer_g_raph("jbzoo/composer-graph@1.0.x-dev");',
            '        jbzoo__phpunit("jbzoo/phpunit@4.0.x-dev");',
            '        maglnet__composer_require_checker("maglnet/composer-require-checker@2.0.0");',
            '        microsoft__tolerant_php_parser("microsoft/tolerant-php-parser@v0.0.20");',
            '        myclabs__deep_copy("myclabs/deep-copy@1.10.1");',
            '        netresearch__jsonmapper("netresearch/jsonmapper@v2.1.0");',
            '        nette__neon("nette/neon@v3.1.2");',
            '        nikic__php_parser("nikic/php-parser@v4.6.0");',
            '        ocramius__package_versions("ocramius/package-versions@1.4.2");',
            '        openlss__lib_array2xml("openlss/lib-array2xml@1.0.0");',
            '        paragonie__random_compat("paragonie/random_compat@v9.99.99");',
            '        pdepend__pdepend("pdepend/pdepend@2.8.0");',
            '        phan__phan("phan/phan@3.0.4");',
            '        phar_io__manifest("phar-io/manifest@1.0.3");',
            '        phar_io__version("phar-io/version@2.0.1");',
            '        php_coveralls__php_coveralls("php-coveralls/php-coveralls@v2.2.0");',
            '        php_cs_fixer__diff("php-cs-fixer/diff@v1.3.0");',
            '        php_cs_fixer__phpunit_constraint_isidenticalstring(["php-cs-fixer/phpunit-constraint-isidenticalstring"]);',
            '        php_cs_fixer__phpunit_constraint_xmlmatchesxsd(["php-cs-fixer/phpunit-constraint-xmlmatchesxsd"]);',
            '        phpcompatibility__php_compatibility("phpcompatibility/php-compatibility@9.3.5");',
            '        phpdocumentor__reflection_common("phpdocumentor/reflection-common@2.2.0");',
            '        phpdocumentor__reflection_docblock("phpdocumentor/reflection-docblock@5.1.0");',
            '        phpdocumentor__type_resolver("phpdocumentor/type-resolver@1.3.0");',
            '        phploc__phploc("phploc/phploc@5.0.0");',
            '        phpmd__phpmd("phpmd/phpmd@2.8.2");',
            '        phpspec__prophecy("phpspec/prophecy@v1.10.3");',
            '        phpstan__phpstan("phpstan/phpstan@0.12.32");',
            '        phpunit__php_code_coverage("phpunit/php-code-coverage@7.0.10");',
            '        phpunit__php_file_iterator("phpunit/php-file-iterator@2.0.2");',
            '        phpunit__php_invoker(["phpunit/php-invoker"]);',
            '        phpunit__php_text_template("phpunit/php-text-template@1.2.1");',
            '        phpunit__php_timer("phpunit/php-timer@2.1.2");',
            '        phpunit__php_token_stream("phpunit/php-token-stream@3.1.1");',
            '        phpunit__phpcov("phpunit/phpcov@6.0.1");',
            '        phpunit__phpunit("phpunit/phpunit@8.5.8");',
            '        povils__phpmnd("povils/phpmnd@v2.2.0");',
            '        psr__container("psr/container@1.0.0");',
            '        psr__event_dispatcher(["psr/event-dispatcher"]);',
            '        psr__http_message("psr/http-message@1.0.1");',
            '        psr__log("psr/log@1.1.3");',
            '        ralouphie__getallheaders("ralouphie/getallheaders@3.0.3");',
            '        sabre__event("sabre/event@5.1.0");',
            '        sebastian__code_unit_reverse_lookup("sebastian/code-unit-reverse-lookup@1.0.1");',
            '        sebastian__comparator("sebastian/comparator@3.0.2");',
            '        sebastian__diff("sebastian/diff@3.0.2");',
            '        sebastian__environment("sebastian/environment@4.2.3");',
            '        sebastian__exporter("sebastian/exporter@3.1.2");',
            '        sebastian__finder_facade("sebastian/finder-facade@1.2.3");',
            '        sebastian__global_state("sebastian/global-state@3.0.0");',
            '        sebastian__object_enumerator("sebastian/object-enumerator@3.0.3");',
            '        sebastian__object_reflector("sebastian/object-reflector@1.1.1");',
            '        sebastian__phpcpd("sebastian/phpcpd@4.1.0");',
            '        sebastian__recursion_context("sebastian/recursion-context@3.0.0");',
            '        sebastian__resource_operations("sebastian/resource-operations@2.0.1");',
            '        sebastian__type("sebastian/type@1.1.3");',
            '        sebastian__version("sebastian/version@2.0.1");',
            '        sensiolabs__security_checker("sensiolabs/security-checker@v6.0.3");',
            '        squizlabs__php_codesniffer("squizlabs/php_codesniffer@3.5.5");',
            '        symfony__config("symfony/config@v5.1.2");',
            '        symfony__console("symfony/console@v4.4.10");',
            '        symfony__dependency_injection("symfony/dependency-injection@v5.1.2");',
            '        symfony__deprecation_contracts("symfony/deprecation-contracts@v2.1.2");',
            '        symfony__event_dispatcher("symfony/event-dispatcher@v4.4.10");',
            '        symfony__event_dispatcher_contracts("symfony/event-dispatcher-contracts@v1.1.7");',
            '        symfony__event_dispatcher_implementation(["symfony/event-dispatcher-implementation"]);',
            '        symfony__expression_language(["symfony/expression-language"]);',
            '        symfony__filesystem("symfony/filesystem@v5.1.2");',
            '        symfony__finder("symfony/finder@v4.4.10");',
            '        symfony__http_client("symfony/http-client@v5.1.2");',
            '        symfony__http_client_contracts("symfony/http-client-contracts@v2.1.2");',
            '        symfony__http_client_implementation(["symfony/http-client-implementation"]);',
            '        symfony__http_kernel(["symfony/http-kernel"]);',
            '        symfony__lock(["symfony/lock"]);',
            '        symfony__mime("symfony/mime@v5.1.2");',
            '        symfony__options_resolver("symfony/options-resolver@v5.1.2");',
            '        symfony__polyfill_ctype("symfony/polyfill-ctype@v1.17.1");',
            '        symfony__polyfill_intl_idn("symfony/polyfill-intl-idn@v1.17.1");',
            '        symfony__polyfill_php70("symfony/polyfill-php70@v1.17.1");',
            '        symfony__polyfill_php72("symfony/polyfill-php72@v1.17.0");',
            '        symfony__polyfill_php73("symfony/polyfill-php73@v1.17.1");',
            '        symfony__polyfill_php80("symfony/polyfill-php80@v1.17.1");',
            '        symfony__proxy_manager_bridge(["symfony/proxy-manager-bridge"]);',
            '        symfony__service_contracts("symfony/service-contracts@v2.1.2");',
            '        symfony__service_implementation(["symfony/service-implementation"]);',
            '        symfony__stopwatch("symfony/stopwatch@v5.1.2");',
            '        theseer__fdomdocument("theseer/fdomdocument@1.6.6");',
            '        theseer__tokenizer("theseer/tokenizer@1.1.3");',
            '        ulrichsg__getopt_php("ulrichsg/getopt-php@v3.3.0");',
            '        vimeo__psalm("vimeo/psalm@3.12.2");',
            '        webmozart__assert("webmozart/assert@1.9.0");',
            '        webmozart__glob("webmozart/glob@4.1.0");',
            '        webmozart__path_util("webmozart/path-util@2.3.0");',
            '        zendframework__zend_httphandlerrunner(["zendframework/zend-httphandlerrunner"]);',
            '    end',
            '    subgraph "PHP Platform"',
            '        PHP("PHP");',
            '        ext_ast("ext-ast");',
            '        ext_ctype("ext-ctype");',
            '        ext_dom("ext-dom");',
            '        ext_exif("ext-exif");',
            '        ext_filter("ext-filter");',
            '        ext_gd("ext-gd");',
            '        ext_iconv("ext-iconv");',
            '        ext_igbinary(["ext-igbinary"]);',
            '        ext_intl("ext-intl");',
            '        ext_json("ext-json");',
            '        ext_libsodium(["ext-libsodium"]);',
            '        ext_libxml("ext-libxml");',
            '        ext_mbstring("ext-mbstring");',
            '        ext_pcre("ext-pcre");',
            '        ext_phar("ext-phar");',
            '        ext_posix("ext-posix");',
            '        ext_reflection("ext-reflection");',
            '        ext_simplexml("ext-simplexml");',
            '        ext_soap("ext-soap");',
            '        ext_spl("ext-spl");',
            '        ext_tokenizer("ext-tokenizer");',
            '        ext_uopz(["ext-uopz"]);',
            '        ext_xdebug(["ext-xdebug"]);',
            '        ext_xml("ext-xml");',
            '        ext_xmlwriter("ext-xmlwriter");',
            '        lib_libxml("lib-libxml");',
            '    end',
        ]), $this->buildGraph([
            'show-php'           => null,
            'show-ext'           => null,
            'show-dev'           => null,
            'show-suggests'      => null,
            'show-lib-versions'  => null,
            'show-link-versions' => null,
        ], __FUNCTION__));
    }

    public function testJBZooToolboxMinimal()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    jbzoo__assets-->jbzoo__data;',
            '    jbzoo__assets-->jbzoo__less;',
            '    jbzoo__assets-->jbzoo__path;',
            '    jbzoo__assets-->jbzoo__utils;',
            '    jbzoo__http_client-->jbzoo__data;',
            '    jbzoo__http_client-.->jbzoo__event;',
            '    jbzoo__image-->jbzoo__data;',
            '    jbzoo__image-->jbzoo__utils;',
            '    jbzoo__less-->jbzoo__data;',
            '    jbzoo__less-->jbzoo__utils;',
            '    jbzoo__less-->wikimedia__less.php;',
            '    jbzoo__path-->jbzoo__data;',
            '    jbzoo__path-->jbzoo__utils;',
            '    jbzoo__toolbox ==> jbzoo__assets;',
            '    jbzoo__toolbox ==> jbzoo__data;',
            '    jbzoo__toolbox ==> jbzoo__event;',
            '    jbzoo__toolbox ==> jbzoo__http_client;',
            '    jbzoo__toolbox ==> jbzoo__image;',
            '    jbzoo__toolbox ==> jbzoo__less;',
            '    jbzoo__toolbox ==> jbzoo__mermaid_php;',
            '    jbzoo__toolbox ==> jbzoo__path;',
            '    jbzoo__toolbox ==> jbzoo__utils;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__toolbox("jbzoo/toolbox");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__assets("jbzoo/assets");',
            '        jbzoo__data("jbzoo/data");',
            '        jbzoo__event("jbzoo/event");',
            '        jbzoo__http_client("jbzoo/http-client");',
            '        jbzoo__image("jbzoo/image");',
            '        jbzoo__less("jbzoo/less");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php");',
            '        jbzoo__path("jbzoo/path");',
            '        jbzoo__utils("jbzoo/utils");',
            '        wikimedia__less.php("wikimedia/less.php");',
            '    end',
        ]), $this->buildGraph([], 'testJBZooToolbox'));
    }

    public function testJBZooToolboxNoDev()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    jbzoo__assets-->|"3.0.x-dev"|jbzoo__less;',
            '    jbzoo__assets-->|"3.0.x-dev"|jbzoo__path;',
            '    jbzoo__assets-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__assets-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__data-->ext_json;',
            '    jbzoo__http_client-->ext_json;',
            '    jbzoo__http_client-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__http_client-. "suggest" .-> jbzoo__event;',
            '    jbzoo__image-->ext_ctype;',
            '    jbzoo__image-->ext_exif;',
            '    jbzoo__image-->ext_gd;',
            '    jbzoo__image-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__image-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__less-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__less-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__less-->|"^3.0.0"|wikimedia__less.php;',
            '    jbzoo__mermaid_php-->ext_json;',
            '    jbzoo__path-->|"4.0.x-dev"|jbzoo__data;',
            '    jbzoo__path-->|"4.0.x-dev"|jbzoo__utils;',
            '    jbzoo__toolbox == "2.0.x-dev" ==> jbzoo__mermaid_php;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__assets;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__event;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__http_client;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__less;',
            '    jbzoo__toolbox == "3.0.x-dev" ==> jbzoo__path;',
            '    jbzoo__toolbox == "4.0.x-dev" ==> jbzoo__data;',
            '    jbzoo__toolbox == "4.0.x-dev" ==> jbzoo__utils;',
            '    jbzoo__toolbox == "5.0.x-dev" ==> jbzoo__image;',
            '    jbzoo__utils-->ext_filter;',
            '    jbzoo__utils-->ext_gd;',
            '    jbzoo__utils-->ext_intl;',
            '    jbzoo__utils-->ext_mbstring;',
            '    jbzoo__utils-->ext_posix;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__toolbox("jbzoo/toolbox");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__assets("jbzoo/assets@3.0.x-dev");',
            '        jbzoo__data("jbzoo/data@4.0.x-dev");',
            '        jbzoo__event("jbzoo/event@3.0.x-dev");',
            '        jbzoo__http_client("jbzoo/http-client@3.0.x-dev");',
            '        jbzoo__image("jbzoo/image@5.0.x-dev");',
            '        jbzoo__less("jbzoo/less@3.0.x-dev");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php@2.0.x-dev");',
            '        jbzoo__path("jbzoo/path@3.0.x-dev");',
            '        jbzoo__utils("jbzoo/utils@4.0.x-dev");',
            '        wikimedia__less.php("wikimedia/less.php@v3.0.0");',
            '    end',
            '    subgraph "PHP Platform"',
            '        ext_ctype("ext-ctype");',
            '        ext_exif("ext-exif");',
            '        ext_filter("ext-filter");',
            '        ext_gd("ext-gd");',
            '        ext_intl("ext-intl");',
            '        ext_json("ext-json");',
            '        ext_mbstring("ext-mbstring");',
            '        ext_posix("ext-posix");',
            '    end',
        ]), $this->buildGraph([
            'show-ext'           => null,
            'show-suggests'      => null,
            'show-lib-versions'  => null,
            'show-link-versions' => null,
        ], 'testJBZooToolbox'));
    }

    public function testRealProject()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    amphp__byte_stream-->amphp__amp;',
            '    codedungeon__phpunit_result_printer-->2bj__phanybar;',
            '    codedungeon__phpunit_result_printer-->codedungeon__php_cli_colors;',
            '    codedungeon__phpunit_result_printer-->hassankhan__config;',
            '    codedungeon__phpunit_result_printer-->symfony__yaml;',
            '    composer__xdebug_handler-->psr__log;',
            '    doctrine__annotations-->doctrine__lexer;',
            '    felixfbecker__advanced_json_rpc-->netresearch__jsonmapper;',
            '    felixfbecker__advanced_json_rpc-->phpdocumentor__reflection_docblock;',
            '    friendsofphp__php_cs_fixer-->composer__semver;',
            '    friendsofphp__php_cs_fixer-->composer__xdebug_handler;',
            '    friendsofphp__php_cs_fixer-->doctrine__annotations;',
            '    friendsofphp__php_cs_fixer-->php_cs_fixer__diff;',
            '    friendsofphp__php_cs_fixer-->symfony__console;',
            '    friendsofphp__php_cs_fixer-->symfony__event_dispatcher;',
            '    friendsofphp__php_cs_fixer-->symfony__filesystem;',
            '    friendsofphp__php_cs_fixer-->symfony__finder;',
            '    friendsofphp__php_cs_fixer-->symfony__options_resolver;',
            '    friendsofphp__php_cs_fixer-->symfony__polyfill_php70;',
            '    friendsofphp__php_cs_fixer-->symfony__polyfill_php72;',
            '    friendsofphp__php_cs_fixer-->symfony__process;',
            '    friendsofphp__php_cs_fixer-->symfony__stopwatch;',
            '    friendsofphp__php_cs_fixer-.->php_cs_fixer__phpunit_constraint_isidenticalstring;',
            '    friendsofphp__php_cs_fixer-.->php_cs_fixer__phpunit_constraint_xmlmatchesxsd;',
            '    friendsofphp__php_cs_fixer-.->symfony__polyfill_mbstring;',
            '    guzzlehttp__guzzle-->guzzlehttp__promises;',
            '    guzzlehttp__guzzle-->guzzlehttp__psr7;',
            '    guzzlehttp__guzzle-->symfony__polyfill_intl_idn;',
            '    guzzlehttp__guzzle-.->psr__log;',
            '    guzzlehttp__psr7-->psr__http_message;',
            '    guzzlehttp__psr7-->ralouphie__getallheaders;',
            '    guzzlehttp__psr7-.->zendframework__zend_httphandlerrunner;',
            '    hassankhan__config-.->symfony__yaml;',
            '    jakub_onderka__php_console_highlighter-->jakub_onderka__php_console_color;',
            '    jbzoo__assets-->jbzoo__data;',
            '    jbzoo__assets-->jbzoo__less;',
            '    jbzoo__assets-->jbzoo__path;',
            '    jbzoo__assets-->jbzoo__utils;',
            '    jbzoo__codestyle-->davidrjonas__composer_lock_diff;',
            '    jbzoo__codestyle-->friendsofphp__php_cs_fixer;',
            '    jbzoo__codestyle-->maglnet__composer_require_checker;',
            '    jbzoo__codestyle-->nette__neon;',
            '    jbzoo__codestyle-->phan__phan;',
            '    jbzoo__codestyle-->php_coveralls__php_coveralls;',
            '    jbzoo__codestyle-->phpcompatibility__php_compatibility;',
            '    jbzoo__codestyle-->phploc__phploc;',
            '    jbzoo__codestyle-->phpmd__phpmd;',
            '    jbzoo__codestyle-->phpstan__phpstan;',
            '    jbzoo__codestyle-->povils__phpmnd;',
            '    jbzoo__codestyle-->sebastian__phpcpd;',
            '    jbzoo__codestyle-->sensiolabs__security_checker;',
            '    jbzoo__codestyle-->squizlabs__php_codesniffer;',
            '    jbzoo__codestyle-->vimeo__psalm;',
            '    jbzoo__composer_g_raph-->jbzoo__data;',
            '    jbzoo__composer_g_raph-->jbzoo__mermaid_php;',
            '    jbzoo__composer_g_raph-->jbzoo__utils;',
            '    jbzoo__composer_g_raph-->symfony__console;',
            '    jbzoo__composer_g_raph-->symfony__process;',
            '    jbzoo__data-.->jbzoo__utils;',
            '    jbzoo__data-.->symfony__yaml;',
            '    jbzoo__http_client-->jbzoo__data;',
            '    jbzoo__http_client-.->guzzlehttp__guzzle;',
            '    jbzoo__http_client-.->jbzoo__event;',
            '    jbzoo__http_client-.->rmccue__requests;',
            '    jbzoo__image-->jbzoo__data;',
            '    jbzoo__image-->jbzoo__utils;',
            '    jbzoo__less-->jbzoo__data;',
            '    jbzoo__less-->jbzoo__utils;',
            '    jbzoo__less-->wikimedia__less.php;',
            '    jbzoo__path-->jbzoo__data;',
            '    jbzoo__path-->jbzoo__utils;',
            '    jbzoo__phpunit-->codedungeon__phpunit_result_printer;',
            '    jbzoo__phpunit-->phpunit__phpcov;',
            '    jbzoo__phpunit-->phpunit__phpunit;',
            '    jbzoo__phpunit-->ulrichsg__getopt_php;',
            '    jbzoo__toolbox ==> guzzlehttp__guzzle;',
            '    jbzoo__toolbox ==> jbzoo__assets;',
            '    jbzoo__toolbox ==> jbzoo__codestyle;',
            '    jbzoo__toolbox ==> jbzoo__composer_g_raph;',
            '    jbzoo__toolbox ==> jbzoo__data;',
            '    jbzoo__toolbox ==> jbzoo__event;',
            '    jbzoo__toolbox ==> jbzoo__http_client;',
            '    jbzoo__toolbox ==> jbzoo__image;',
            '    jbzoo__toolbox ==> jbzoo__less;',
            '    jbzoo__toolbox ==> jbzoo__mermaid_php;',
            '    jbzoo__toolbox ==> jbzoo__path;',
            '    jbzoo__toolbox ==> jbzoo__phpunit;',
            '    jbzoo__toolbox ==> jbzoo__utils;',
            '    jbzoo__toolbox ==> rmccue__requests;',
            '    jbzoo__toolbox ==> roave__security_advisories;',
            '    jbzoo__utils-.->jbzoo__data;',
            '    jbzoo__utils-.->symfony__polyfill_mbstring;',
            '    jbzoo__utils-.->symfony__process;',
            '    maglnet__composer_require_checker-->nikic__php_parser;',
            '    maglnet__composer_require_checker-->symfony__console;',
            '    maglnet__composer_require_checker-->webmozart__glob;',
            '    ocramius__package_versions-->composer_plugin_api;',
            '    pdepend__pdepend-->symfony__config;',
            '    pdepend__pdepend-->symfony__dependency_injection;',
            '    pdepend__pdepend-->symfony__filesystem;',
            '    phan__phan-->composer__semver;',
            '    phan__phan-->composer__xdebug_handler;',
            '    phan__phan-->felixfbecker__advanced_json_rpc;',
            '    phan__phan-->microsoft__tolerant_php_parser;',
            '    phan__phan-->netresearch__jsonmapper;',
            '    phan__phan-->sabre__event;',
            '    phan__phan-->symfony__console;',
            '    phan__phan-->symfony__polyfill_mbstring;',
            '    phar_io__manifest-->phar_io__version;',
            '    php_coveralls__php_coveralls-->guzzlehttp__guzzle;',
            '    php_coveralls__php_coveralls-->psr__log;',
            '    php_coveralls__php_coveralls-->symfony__config;',
            '    php_coveralls__php_coveralls-->symfony__console;',
            '    php_coveralls__php_coveralls-->symfony__stopwatch;',
            '    php_coveralls__php_coveralls-->symfony__yaml;',
            '    php_coveralls__php_coveralls-.->symfony__http_kernel;',
            '    phpcompatibility__php_compatibility-->squizlabs__php_codesniffer;',
            '    phpcompatibility__php_compatibility-.->dealerdirect__phpcodesniffer_composer_installer;',
            '    phpcompatibility__php_compatibility-.->roave__security_advisories;',
            '    phpdocumentor__reflection_docblock-->phpdocumentor__reflection_common;',
            '    phpdocumentor__reflection_docblock-->phpdocumentor__type_resolver;',
            '    phpdocumentor__reflection_docblock-->webmozart__assert;',
            '    phpdocumentor__type_resolver-->phpdocumentor__reflection_common;',
            '    phploc__phploc-->sebastian__finder_facade;',
            '    phploc__phploc-->sebastian__version;',
            '    phploc__phploc-->symfony__console;',
            '    phpmd__phpmd-->composer__xdebug_handler;',
            '    phpmd__phpmd-->pdepend__pdepend;',
            '    phpspec__prophecy-->doctrine__instantiator;',
            '    phpspec__prophecy-->phpdocumentor__reflection_docblock;',
            '    phpspec__prophecy-->sebastian__comparator;',
            '    phpspec__prophecy-->sebastian__recursion_context;',
            '    phpunit__php_code_coverage-->phpunit__php_file_iterator;',
            '    phpunit__php_code_coverage-->phpunit__php_text_template;',
            '    phpunit__php_code_coverage-->phpunit__php_token_stream;',
            '    phpunit__php_code_coverage-->sebastian__code_unit_reverse_lookup;',
            '    phpunit__php_code_coverage-->sebastian__environment;',
            '    phpunit__php_code_coverage-->sebastian__version;',
            '    phpunit__php_code_coverage-->theseer__tokenizer;',
            '    phpunit__phpcov-->phpunit__php_code_coverage;',
            '    phpunit__phpcov-->phpunit__phpunit;',
            '    phpunit__phpcov-->sebastian__diff;',
            '    phpunit__phpcov-->sebastian__finder_facade;',
            '    phpunit__phpcov-->sebastian__version;',
            '    phpunit__phpcov-->symfony__console;',
            '    phpunit__phpunit-->doctrine__instantiator;',
            '    phpunit__phpunit-->myclabs__deep_copy;',
            '    phpunit__phpunit-->phar_io__manifest;',
            '    phpunit__phpunit-->phar_io__version;',
            '    phpunit__phpunit-->phpspec__prophecy;',
            '    phpunit__phpunit-->phpunit__php_code_coverage;',
            '    phpunit__phpunit-->phpunit__php_file_iterator;',
            '    phpunit__phpunit-->phpunit__php_text_template;',
            '    phpunit__phpunit-->phpunit__php_timer;',
            '    phpunit__phpunit-->sebastian__comparator;',
            '    phpunit__phpunit-->sebastian__diff;',
            '    phpunit__phpunit-->sebastian__environment;',
            '    phpunit__phpunit-->sebastian__exporter;',
            '    phpunit__phpunit-->sebastian__global_state;',
            '    phpunit__phpunit-->sebastian__object_enumerator;',
            '    phpunit__phpunit-->sebastian__resource_operations;',
            '    phpunit__phpunit-->sebastian__type;',
            '    phpunit__phpunit-->sebastian__version;',
            '    phpunit__phpunit-.->phpunit__php_invoker;',
            '    povils__phpmnd-->jakub_onderka__php_console_highlighter;',
            '    povils__phpmnd-->nikic__php_parser;',
            '    povils__phpmnd-->phpunit__php_timer;',
            '    povils__phpmnd-->symfony__console;',
            '    povils__phpmnd-->symfony__finder;',
            '    sebastian__comparator-->sebastian__diff;',
            '    sebastian__comparator-->sebastian__exporter;',
            '    sebastian__exporter-->sebastian__recursion_context;',
            '    sebastian__finder_facade-->symfony__finder;',
            '    sebastian__finder_facade-->theseer__fdomdocument;',
            '    sebastian__global_state-->sebastian__object_reflector;',
            '    sebastian__global_state-->sebastian__recursion_context;',
            '    sebastian__object_enumerator-->sebastian__object_reflector;',
            '    sebastian__object_enumerator-->sebastian__recursion_context;',
            '    sebastian__phpcpd-->phpunit__php_timer;',
            '    sebastian__phpcpd-->sebastian__finder_facade;',
            '    sebastian__phpcpd-->sebastian__version;',
            '    sebastian__phpcpd-->symfony__console;',
            '    sensiolabs__security_checker-->symfony__console;',
            '    sensiolabs__security_checker-->symfony__http_client;',
            '    sensiolabs__security_checker-->symfony__mime;',
            '    sensiolabs__security_checker-->symfony__polyfill_ctype;',
            '    symfony__config-->symfony__deprecation_contracts;',
            '    symfony__config-->symfony__filesystem;',
            '    symfony__config-->symfony__polyfill_ctype;',
            '    symfony__config-->symfony__polyfill_php80;',
            '    symfony__config-.->symfony__yaml;',
            '    symfony__console-->symfony__polyfill_mbstring;',
            '    symfony__console-->symfony__polyfill_php73;',
            '    symfony__console-->symfony__polyfill_php80;',
            '    symfony__console-->symfony__service_contracts;',
            '    symfony__console-.->psr__log;',
            '    symfony__console-.->symfony__event_dispatcher;',
            '    symfony__console-.->symfony__lock;',
            '    symfony__console-.->symfony__process;',
            '    symfony__dependency_injection-->psr__container;',
            '    symfony__dependency_injection-->symfony__deprecation_contracts;',
            '    symfony__dependency_injection-->symfony__polyfill_php80;',
            '    symfony__dependency_injection-->symfony__service_contracts;',
            '    symfony__dependency_injection-.->symfony__config;',
            '    symfony__dependency_injection-.->symfony__expression_language;',
            '    symfony__dependency_injection-.->symfony__finder;',
            '    symfony__dependency_injection-.->symfony__proxy_manager_bridge;',
            '    symfony__dependency_injection-.->symfony__yaml;',
            '    symfony__event_dispatcher-->symfony__event_dispatcher_contracts;',
            '    symfony__event_dispatcher-.->symfony__dependency_injection;',
            '    symfony__event_dispatcher-.->symfony__http_kernel;',
            '    symfony__event_dispatcher_contracts-.->psr__event_dispatcher;',
            '    symfony__event_dispatcher_contracts-.->symfony__event_dispatcher_implementation;',
            '    symfony__filesystem-->symfony__polyfill_ctype;',
            '    symfony__http_client-->psr__log;',
            '    symfony__http_client-->symfony__http_client_contracts;',
            '    symfony__http_client-->symfony__polyfill_php73;',
            '    symfony__http_client-->symfony__polyfill_php80;',
            '    symfony__http_client-->symfony__service_contracts;',
            '    symfony__http_client_contracts-.->symfony__http_client_implementation;',
            '    symfony__mime-->symfony__polyfill_intl_idn;',
            '    symfony__mime-->symfony__polyfill_mbstring;',
            '    symfony__mime-->symfony__polyfill_php80;',
            '    symfony__options_resolver-->symfony__deprecation_contracts;',
            '    symfony__options_resolver-->symfony__polyfill_php80;',
            '    symfony__polyfill_intl_idn-->symfony__polyfill_mbstring;',
            '    symfony__polyfill_intl_idn-->symfony__polyfill_php72;',
            '    symfony__polyfill_php70-->paragonie__random_compat;',
            '    symfony__process-->symfony__polyfill_php80;',
            '    symfony__service_contracts-->psr__container;',
            '    symfony__service_contracts-.->symfony__service_implementation;',
            '    symfony__stopwatch-->symfony__service_contracts;',
            '    symfony__yaml-->symfony__deprecation_contracts;',
            '    symfony__yaml-->symfony__polyfill_ctype;',
            '    symfony__yaml-.->symfony__console;',
            '    vimeo__psalm-->amphp__amp;',
            '    vimeo__psalm-->amphp__byte_stream;',
            '    vimeo__psalm-->composer__semver;',
            '    vimeo__psalm-->composer__xdebug_handler;',
            '    vimeo__psalm-->felixfbecker__advanced_json_rpc;',
            '    vimeo__psalm-->felixfbecker__language_server_protocol;',
            '    vimeo__psalm-->netresearch__jsonmapper;',
            '    vimeo__psalm-->nikic__php_parser;',
            '    vimeo__psalm-->ocramius__package_versions;',
            '    vimeo__psalm-->openlss__lib_array2xml;',
            '    vimeo__psalm-->sebastian__diff;',
            '    vimeo__psalm-->symfony__console;',
            '    vimeo__psalm-->webmozart__glob;',
            '    vimeo__psalm-->webmozart__path_util;',
            '    webmozart__assert-->symfony__polyfill_ctype;',
            '    webmozart__glob-->webmozart__path_util;',
            '    webmozart__path_util-->webmozart__assert;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__toolbox("jbzoo/toolbox");',
            '    end',
            '    subgraph "Required"',
            '        guzzlehttp__guzzle("guzzlehttp/guzzle");',
            '        jbzoo__assets("jbzoo/assets");',
            '        jbzoo__data("jbzoo/data");',
            '        jbzoo__event("jbzoo/event");',
            '        jbzoo__http_client("jbzoo/http-client");',
            '        jbzoo__image("jbzoo/image");',
            '        jbzoo__less("jbzoo/less");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php");',
            '        jbzoo__path("jbzoo/path");',
            '        jbzoo__utils("jbzoo/utils");',
            '        rmccue__requests("rmccue/requests");',
            '        roave__security_advisories("roave/security-advisories");',
            '        symfony__polyfill_mbstring("symfony/polyfill-mbstring");',
            '        symfony__process("symfony/process");',
            '        symfony__yaml("symfony/yaml");',
            '        wikimedia__less.php("wikimedia/less.php");',
            '    end',
            '    subgraph "Required Dev"',
            '        2bj__phanybar("2bj/phanybar");',
            '        amphp__amp("amphp/amp");',
            '        amphp__byte_stream("amphp/byte-stream");',
            '        codedungeon__php_cli_colors("codedungeon/php-cli-colors");',
            '        codedungeon__phpunit_result_printer("codedungeon/phpunit-result-printer");',
            '        composer__semver("composer/semver");',
            '        composer__xdebug_handler("composer/xdebug-handler");',
            '        composer_plugin_api(["composer-plugin-api"]);',
            '        davidrjonas__composer_lock_diff("davidrjonas/composer-lock-diff");',
            '        dealerdirect__phpcodesniffer_composer_installer(["dealerdirect/phpcodesniffer-composer-installer"]);',
            '        doctrine__annotations("doctrine/annotations");',
            '        doctrine__instantiator("doctrine/instantiator");',
            '        doctrine__lexer("doctrine/lexer");',
            '        felixfbecker__advanced_json_rpc("felixfbecker/advanced-json-rpc");',
            '        felixfbecker__language_server_protocol("felixfbecker/language-server-protocol");',
            '        friendsofphp__php_cs_fixer("friendsofphp/php-cs-fixer");',
            '        guzzlehttp__promises("guzzlehttp/promises");',
            '        guzzlehttp__psr7("guzzlehttp/psr7");',
            '        hassankhan__config("hassankhan/config");',
            '        jakub_onderka__php_console_color("jakub-onderka/php-console-color");',
            '        jakub_onderka__php_console_highlighter("jakub-onderka/php-console-highlighter");',
            '        jbzoo__codestyle("jbzoo/codestyle");',
            '        jbzoo__composer_g_raph("jbzoo/composer-graph");',
            '        jbzoo__phpunit("jbzoo/phpunit");',
            '        maglnet__composer_require_checker("maglnet/composer-require-checker");',
            '        microsoft__tolerant_php_parser("microsoft/tolerant-php-parser");',
            '        myclabs__deep_copy("myclabs/deep-copy");',
            '        netresearch__jsonmapper("netresearch/jsonmapper");',
            '        nette__neon("nette/neon");',
            '        nikic__php_parser("nikic/php-parser");',
            '        ocramius__package_versions("ocramius/package-versions");',
            '        openlss__lib_array2xml("openlss/lib-array2xml");',
            '        paragonie__random_compat("paragonie/random_compat");',
            '        pdepend__pdepend("pdepend/pdepend");',
            '        phan__phan("phan/phan");',
            '        phar_io__manifest("phar-io/manifest");',
            '        phar_io__version("phar-io/version");',
            '        php_coveralls__php_coveralls("php-coveralls/php-coveralls");',
            '        php_cs_fixer__diff("php-cs-fixer/diff");',
            '        php_cs_fixer__phpunit_constraint_isidenticalstring(["php-cs-fixer/phpunit-constraint-isidenticalstring"]);',
            '        php_cs_fixer__phpunit_constraint_xmlmatchesxsd(["php-cs-fixer/phpunit-constraint-xmlmatchesxsd"]);',
            '        phpcompatibility__php_compatibility("phpcompatibility/php-compatibility");',
            '        phpdocumentor__reflection_common("phpdocumentor/reflection-common");',
            '        phpdocumentor__reflection_docblock("phpdocumentor/reflection-docblock");',
            '        phpdocumentor__type_resolver("phpdocumentor/type-resolver");',
            '        phploc__phploc("phploc/phploc");',
            '        phpmd__phpmd("phpmd/phpmd");',
            '        phpspec__prophecy("phpspec/prophecy");',
            '        phpstan__phpstan("phpstan/phpstan");',
            '        phpunit__php_code_coverage("phpunit/php-code-coverage");',
            '        phpunit__php_file_iterator("phpunit/php-file-iterator");',
            '        phpunit__php_invoker(["phpunit/php-invoker"]);',
            '        phpunit__php_text_template("phpunit/php-text-template");',
            '        phpunit__php_timer("phpunit/php-timer");',
            '        phpunit__php_token_stream("phpunit/php-token-stream");',
            '        phpunit__phpcov("phpunit/phpcov");',
            '        phpunit__phpunit("phpunit/phpunit");',
            '        povils__phpmnd("povils/phpmnd");',
            '        psr__container("psr/container");',
            '        psr__event_dispatcher(["psr/event-dispatcher"]);',
            '        psr__http_message("psr/http-message");',
            '        psr__log("psr/log");',
            '        ralouphie__getallheaders("ralouphie/getallheaders");',
            '        sabre__event("sabre/event");',
            '        sebastian__code_unit_reverse_lookup("sebastian/code-unit-reverse-lookup");',
            '        sebastian__comparator("sebastian/comparator");',
            '        sebastian__diff("sebastian/diff");',
            '        sebastian__environment("sebastian/environment");',
            '        sebastian__exporter("sebastian/exporter");',
            '        sebastian__finder_facade("sebastian/finder-facade");',
            '        sebastian__global_state("sebastian/global-state");',
            '        sebastian__object_enumerator("sebastian/object-enumerator");',
            '        sebastian__object_reflector("sebastian/object-reflector");',
            '        sebastian__phpcpd("sebastian/phpcpd");',
            '        sebastian__recursion_context("sebastian/recursion-context");',
            '        sebastian__resource_operations("sebastian/resource-operations");',
            '        sebastian__type("sebastian/type");',
            '        sebastian__version("sebastian/version");',
            '        sensiolabs__security_checker("sensiolabs/security-checker");',
            '        squizlabs__php_codesniffer("squizlabs/php_codesniffer");',
            '        symfony__config("symfony/config");',
            '        symfony__console("symfony/console");',
            '        symfony__dependency_injection("symfony/dependency-injection");',
            '        symfony__deprecation_contracts("symfony/deprecation-contracts");',
            '        symfony__event_dispatcher("symfony/event-dispatcher");',
            '        symfony__event_dispatcher_contracts("symfony/event-dispatcher-contracts");',
            '        symfony__event_dispatcher_implementation(["symfony/event-dispatcher-implementation"]);',
            '        symfony__expression_language(["symfony/expression-language"]);',
            '        symfony__filesystem("symfony/filesystem");',
            '        symfony__finder("symfony/finder");',
            '        symfony__http_client("symfony/http-client");',
            '        symfony__http_client_contracts("symfony/http-client-contracts");',
            '        symfony__http_client_implementation(["symfony/http-client-implementation"]);',
            '        symfony__http_kernel(["symfony/http-kernel"]);',
            '        symfony__lock(["symfony/lock"]);',
            '        symfony__mime("symfony/mime");',
            '        symfony__options_resolver("symfony/options-resolver");',
            '        symfony__polyfill_ctype("symfony/polyfill-ctype");',
            '        symfony__polyfill_intl_idn("symfony/polyfill-intl-idn");',
            '        symfony__polyfill_php70("symfony/polyfill-php70");',
            '        symfony__polyfill_php72("symfony/polyfill-php72");',
            '        symfony__polyfill_php73("symfony/polyfill-php73");',
            '        symfony__polyfill_php80("symfony/polyfill-php80");',
            '        symfony__proxy_manager_bridge(["symfony/proxy-manager-bridge"]);',
            '        symfony__service_contracts("symfony/service-contracts");',
            '        symfony__service_implementation(["symfony/service-implementation"]);',
            '        symfony__stopwatch("symfony/stopwatch");',
            '        theseer__fdomdocument("theseer/fdomdocument");',
            '        theseer__tokenizer("theseer/tokenizer");',
            '        ulrichsg__getopt_php("ulrichsg/getopt-php");',
            '        vimeo__psalm("vimeo/psalm");',
            '        webmozart__assert("webmozart/assert");',
            '        webmozart__glob("webmozart/glob");',
            '        webmozart__path_util("webmozart/path-util");',
            '        zendframework__zend_httphandlerrunner(["zendframework/zend-httphandlerrunner"]);',
            '    end',
        ]), $this->buildGraph([
            'show-dev'      => null,
            'show-suggests' => null,
        ], __FUNCTION__));
    }

    public function testRealProjectMinimal()
    {
        isSame(implode("\n", [
            'graph LR;',
            '    jbzoo__assets-->jbzoo__data;',
            '    jbzoo__assets-->jbzoo__less;',
            '    jbzoo__assets-->jbzoo__path;',
            '    jbzoo__assets-->jbzoo__utils;',
            '    jbzoo__http_client-->jbzoo__data;',
            '    jbzoo__http_client-.->jbzoo__event;',
            '    jbzoo__image-->jbzoo__data;',
            '    jbzoo__image-->jbzoo__utils;',
            '    jbzoo__less-->jbzoo__data;',
            '    jbzoo__less-->jbzoo__utils;',
            '    jbzoo__less-->wikimedia__less.php;',
            '    jbzoo__path-->jbzoo__data;',
            '    jbzoo__path-->jbzoo__utils;',
            '    jbzoo__toolbox ==> jbzoo__assets;',
            '    jbzoo__toolbox ==> jbzoo__data;',
            '    jbzoo__toolbox ==> jbzoo__event;',
            '    jbzoo__toolbox ==> jbzoo__http_client;',
            '    jbzoo__toolbox ==> jbzoo__image;',
            '    jbzoo__toolbox ==> jbzoo__less;',
            '    jbzoo__toolbox ==> jbzoo__mermaid_php;',
            '    jbzoo__toolbox ==> jbzoo__path;',
            '    jbzoo__toolbox ==> jbzoo__utils;',
            '',
            '    subgraph "Your Package"',
            '        jbzoo__toolbox("jbzoo/toolbox");',
            '    end',
            '    subgraph "Required"',
            '        jbzoo__assets("jbzoo/assets");',
            '        jbzoo__data("jbzoo/data");',
            '        jbzoo__event("jbzoo/event");',
            '        jbzoo__http_client("jbzoo/http-client");',
            '        jbzoo__image("jbzoo/image");',
            '        jbzoo__less("jbzoo/less");',
            '        jbzoo__mermaid_php("jbzoo/mermaid-php");',
            '        jbzoo__path("jbzoo/path");',
            '        jbzoo__utils("jbzoo/utils");',
            '        wikimedia__less.php("wikimedia/less.php");',
            '    end',
        ]), $this->buildGraph([], 'testRealProject'));
    }
}
